### ISSUE TITLE
Feasiblity of porting arcore-android sdk to other linux based OS

### ISSUE THREAD

**Issue by thusharajayakumar** [google-ar/arcore-android-sdk#1087]
I am checking the feasiblity of extendidng arcore for android to other linux based OS.
Is this porting feasible?
If yes, What all dependencies will be there in this porting, that needs ti be considered? 

Thanks in advance

**Comment by mpottinger** [comment]
@thusharajayakumar ARCore is closed source, so it is unlikely it will be ported. 

What you are looking for are open source SLAM frameworks, or a tracking camera like the Intel T265, or ZED mini which does tracking just like arcore, but there is a lot more DIY work involved as well.

I don't think Google would have any motivation to port it to PC, because it is actually a derivative of the SLAM methods already available on PC

**Comment by devbridie** [comment]
There are no plans to expand support to other platforms at the moment.
