### ISSUE TITLE
Object is appearing black

### ISSUE THREAD

**Issue by biklas7** [google-ar/arcore-android-sdk#109]
I'm doing a project based on the sample provided here and trying to load an object from an .obj file with a .jpg texture and it is appearing black no matter what I do.

I'm no expert in Open GL so I'm using the same code of the sample.

Here are the files https://drive.google.com/file/d/1H-Z3nJUNKyHp52yS0v8ZshJAKeEzQMSx/view?usp=sharing

**Comment by biklas7** [comment]
Sorry, it was another issue with the Blender exporation

**Comment by khurramengr** [comment]
@biklas7 the "Andy.obj" from sample is appearing black to me as well.
How did you fix that issue?

**Comment by WillowZAR** [comment]
OK

On 29 Nov 2018 07:41, "Khurram Shehzad" <notifications@github.com> wrote:

@biklas7 <https://github.com/biklas7> the "Andy.obj" from sample is
appearing black to me as well.
How did you fix that issue?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google-ar/arcore-android-sdk/issues/109#issuecomment-442713418>,
or mute the thread

**Comment by khurramengr** [comment]
Okay, I've managed to fix it myself. In my case **Light Estimation was disabled in Configuration**
