### ISSUE TITLE
Occlusion doesn't work anymore when CameraConfig.DepthSensorUsage set to DO_NOT_USE

### ISSUE THREAD

**Issue by agGitHub** [google-ar/arcore-android-sdk#1193]
### SPECIFIC ISSUE ENCOUNTERED

Hi,

When CameraConfig.DepthSensorUsage is set to DO_NOT_USE, it seems that the occlusion doesn't work anymore.

That is weird as frame.acquireDepthImage() works when CameraConfig.DepthSensorUsage is set to DO_NOT_USE.

So:

`backgroundRenderer.updateCameraDepthTexture(depthImage);`

should also work.

All the code in BackgroundRenderer seems properly executed. I don't understand why occlusion doesn't work.

Any idea about the origin of this problem and a solution to solve it ?

Thanks.

### STEPS TO REPRODUCE THE ISSUE
 1. In  configureSession() add the following code :

```
CameraConfigFilter filter = new CameraConfigFilter(session);
filter.setDepthSensorUsage(EnumSet.of(CameraConfig.DepthSensorUsage.DO_NOT_USE));
List<CameraConfig> cameraConfigList = session.getSupportedCameraConfigs(filter);
session.setCameraConfig(cameraConfigList.get(0));
```

 2. Set useDepthForOcclusion to true 
 
3. See that occlusion doesn't work when placing an object in AR scene.

### WORKAROUNDS (IF ANY)
Not found.

**Comment by devbridie** [comment]
I can't repro; please check my changes in [my repro](https://github.com/devbridie/arcore-android-sdk/tree/issue-1193). I'm seeing occlusion working after placing a pawn in the scene and trying to occlude it with a real-world object.

Are you seeing the depth visualization (i.e. the heat map) at all? That's the visualisation for [`u_CameraDepthTexture` in the occlusion shader ](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/hello_ar_java/app/src/main/assets/shaders/occlusion.frag).

**Comment by agGitHub** [comment]
Thanks. Unfortunately, I already implemented these modifications (I double checked and did exactly your modifications) in the hello_ar_java project (ARCore 1.22) but I still have the problem. I have this problem on both my Samsung devices S10+ and S20+. Yes, I can see the depth map (heat map) in the hello_ar_java project on my both devices. Note that on my Samsung devices the resolution of the depthImage is lower (90x160) when DO_NOT_USE is used, instead of 360x640 when it is not used. I don't know of it might have an influence. On what device do you check ? Thanks.

**Comment by devbridie** [comment]
I'm using a Pixel 4 XL. I asked a colleague to try my fork; couldn't repro either (using Galaxy S20+ 5G). Since you can see the depth map, I don't think this is an ARCore API issue.

Some suggestions:

* Verify that `USE_OCCLUSION` is 1 [here](https://github.com/google-ar/arcore-android-sdk/blob/eaa85941f2d724c60671bf94f46de7178baba7e6/samples/hello_ar_java/app/src/main/java/com/google/ar/core/examples/java/common/samplerender/arcore/BackgroundRenderer.java#L162)
* Ensure [updateCameraDepthTexture](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/hello_ar_java/app/src/main/java/com/google/ar/core/examples/java/common/samplerender/arcore/BackgroundRenderer.java#L195) is being hit
* Verify that the `#if USE_OCCLUSION` parts are being hit in [`occlusion.frag`](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/hello_ar_java/app/src/main/assets/shaders/occlusion.frag) by tweaking values, though this is a little difficult
