### ISSUE TITLE
Can the webpage HTML5 video element be loaded into AR view ?

### ISSUE THREAD

**Issue by senthil5053** [google-ar/arcore-android-sdk#1205]
I was using SceneForm SDK for the AR capabilities on my app. I've tried loading the WebView on ViewRenderable and it worked fine with no issue. I could able to load any HTTP/HTTPS webpages. However when tried to load the webpage that uses HTML5 video element in it, then I just see the black screen instead of the actual video content. BTW, audio content plays fine. 

Can the HTML5 video element be loaded into AR view ? Any suggestion on how this can be achieved ?

**Comment by devbridie** [comment]
I'd guess that the video rendering might use hardware rendering, which would poke a hole through the view layer so that the video can be thrown at the canvas a quickly as possible. This might explain the behavior you're seeing and is an avenue you could investigate.

Unfortunately, Google doesn't offer support for Sceneform after [open-sourcing the SDK](https://github.com/google-ar/sceneform-android-sdk), so this issue is off-topic here.
