### ISSUE TITLE
Blackscreen when I try to integrate ARCore to my project

### ISSUE THREAD

**Issue by abhishekk06** [google-ar/arcore-android-sdk#1210]
Hi,
 
 I am trying to place an anchor once the object is detected but for some reason, I am not able to implement Instantplacement in my project. I am following the BKM shared on the developer guide but as soon I enable ARCore my screen goes all black. Can you please take a look?
 
I have captured the error signature and my repo path in the link given below.

 https://stackoverflow.com/questions/66602054/how-to-use-arcore-and-camerax-at-the-same-time

**Comment by abhishekk06** [comment]
Hi Guys,

I was hoping to get a reply. I am stuck in the same place for a long time.

**Comment by abhishekk06** [comment]
tagging @nvictornvictor since github marked you as #1 contributor to the repo

**Comment by devbridie** [comment]
The CameraX is not (easily) compatible with ARCore. Sharing the camera with ARCore *must* be done according to [the shared camera documentation](https://developers.google.com/ar/develop/java/camera-sharing) for ARCore compatibility:

1. Using [createARDeviceStateCallback](https://developers.google.com/ar/reference/java/com/google/ar/core/SharedCamera#createARDeviceStateCallback(android.hardware.camera2.CameraDevice.StateCallback,%20android.os.Handler)) which wraps [`CameraDevice.StateCallback`](https://developer.android.com/reference/android/hardware/camera2/CameraDevice.StateCallback). This [doesn't seem to be exposed in CameraX's implementation in camera2](https://github.com/androidx/androidx/blob/androidx-main/camera/camera-camera2/src/main/java/androidx/camera/camera2/internal/Camera2CameraImpl.java#L945).
2. Same story for [setCaptureCallback](https://developers.google.com/ar/reference/java/com/google/ar/core/SharedCamera#public-void-setcapturecallback-cameracapturesession.capturecallback-appcapturecallback,-handler-apphandler).

The [Camera2 sample](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/shared_camera_java/app/src/main/java/com/google/ar/core/examples/java/sharedcamera/SharedCameraActivity.java) shows how this is done without CameraX. 

However, since your application seems to analyze camera frames, do you need camera sharing at all? You could use [acquireCameraImage](https://developers.google.com/ar/reference/java/com/google/ar/core/Frame#public-image-acquirecameraimage) as an image source en lieu of CameraX' ImageAnalysis usecase.

**Comment by abhishekk06** [comment]
Hi Dereck,

Only reason I used cameraX over camera2 is because I feel it is much more
simple to use.

Let me go over the shared camera documentation and get back to you.

Regards
Abhishek

**Comment by abhishekk06** [comment]
Hi @devbridie,

Any idea, how do I use the set analyzer function if in case I move to acquireCameraImage?

`
val imageAnalysis = ImageAnalysis.Builder()
                .setTargetAspectRatio(AspectRatio.RATIO_4_3)
                .setTargetRotation(view_finder.display.rotation)
                .setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST)
                .build()
                
                imageAnalysis.setAnalyzer(executor, ImageAnalysis.Analyzer { image ->
                if (!::bitmapBuffer.isInitialized) {
                    // The image rotation and RGB image buffer are initialized only once
                    // the analyzer has started running
                    imageRotationDegrees = image.imageInfo.rotationDegrees
                    bitmapBuffer = Bitmap.createBitmap(
                            image.width, image.height, Bitmap.Config.ARGB_8888
                    )
                }
`

**Comment by devbridie** [comment]
[`session.update()`](https://developers.google.com/ar/reference/java/com/google/ar/core/Session#update()) returns a Frame, which you can use [`frame.acquireFrameImage()`](https://developers.google.com/ar/reference/java/com/google/ar/core/Frame#acquireCameraImage()) on. This exposes a [`android.media.Image`](https://developer.android.com/reference/android/media/Image).

**Comment by abhishekk06** [comment]
Will it be possible for me to have quick sync? I am not sure I understood correctly how to replace cameraX usage with ARCore session functions.

**Comment by abhishekk06** [comment]
Hi @devbridie 

I have done changes in order to move away from CameraX usage. Since I am pretty new to android development and Camera API. I would request you to please take a look. 

https://github.com/abhishekk06/sandbox/commit/3e510791134db2c021778a0c6806effca6fa2197

**Comment by abhishekk06** [comment]
Also, I am still not very much sure of how to convert images from Yuv to RGB so that I can pass it as input to my TFlite model.

**Comment by fredsa** [comment]
If you require access to the camera while ARCore is running, then suggested you start with the [`shared_camera_java`](https://github.com/google-ar/arcore-android-sdk/tree/master/samples/shared_camera_java) app. Confirm that the app is working as expected (no black screen), then slowly add your desired functionality.

If you don't require access to the camera (for example to set custom surfaces), for example if you want to just access the already available 640x480 (VGA) CPU image, you can start with the much simpler [`computer_vision_*`](https://github.com/google-ar/arcore-android-sdk/tree/master/samples) samples.

**Comment by abhishekk06** [comment]
Hi @fredsa,

So the main idea is to use the TFlite model to detect an object and once the desired object is found. I want to place an anchor in the given location using Frame.hitTestInstantPlacement(). 

As per the last comment from @devbridie, I think shared_camera is not supported for instant placement. If in case you guys have any other suggestions or can take a look at my code it will be really great.

**Comment by abhishekk06** [comment]
Hi Guys,

After a few cleanups (with help from hannesa2), I am hitting "ArStatusErrorSpace::AR_ERROR_MISSING_GL_CONTEXT" when I try to update the frame to capture images and fwd them to the TFlite model. Can you please suggest how to proceed further?

**Comment by devbridie** [comment]
[MissingGlContextException](https://developers.google.com/ar/reference/java/com/google/ar/core/exceptions/MissingGlContextException) occurs when the gl context isn't available, ie, the operation that throws this exception requires that you are on a [gl thread](https://developer.android.com/reference/android/opengl/GLSurfaceView.Renderer). This is needed because `update` causes a texture write which is only valid in a GL context.

**Comment by abhishekk06** [comment]
Hi @devbridie,

I am hitting null pointer exception when I try to setup renderer. Can you take a look at my changes?

https://github.com/abhishekk06/sandbox/commit/7c4de37868429fcfe3346630f1a34562612f0283

**Comment by abhishekk06** [comment]
*Update*

I got passed null ptr exception. I was mainly missing assignments and now I am back to the same old issue. :/ 
Am i missing something very basic while creating GLthread?

![image](https://user-images.githubusercontent.com/55446334/111364430-95eca700-8667-11eb-9e75-15592b1dc0f1.png)

https://github.com/abhishekk06/sandbox/commit/3593b99e8a74ca8142ae5bf7f5dba3984a00a087

**Comment by fredsa** [comment]
Closing this issue as the original problem (black screen) has been resolved.

As for `AR_ERROR_MISSING_GL_CONTEXT`, this indicates that the current thread is not the one that contains the GL context.   In your last stack track, the thread that's calling `Session.update` requires the GL context, but does not have it. This implies that this call is being made on a different thread than the one that has the GL context.

**Comment by abhishekk06** [comment]
I am not sure how I am calling GL Context from a different context. I am initializing surface view in init and I only have one class implemented in this case.

**Comment by abhishekk06** [comment]
It will be really great if you can find time from your busy schedule and review my code.

**Comment by fredsa** [comment]
From your stack trace it looks like you're calling `Session.update` inside a callback. Callbacks usually run a different thread that the main one with the GL context.

The call to `Session.update` must happen on the thread that has the GL context. Suggest moving the call so that it does not happen inside the callback.

**Comment by abhishekk06** [comment]
Hi @devbridie / @fredsa ,

@hannesa2 and I were able to get pass the 'MISSING_GL_CONTEXT' error by moving the call back to another GLthread. Now we are hitting 'ArStatusErrorSpace::AR_ERROR_TEXTURE_NOT_SET' and as per [this](https://github.com/google-ar/arcore-android-sdk/issues/1170), I tried calling glGenTexture() from onPause() but I am again getting black screen and "Invalid ray produced by view data!"

Please share your inputs.

**Comment by fredsa** [comment]
Make sure you are calling `session.setCameraTextureName` (or `session.setCameraTextureNames`).

**Comment by fredsa** [comment]
In general, recommend going back to a working example (e.g. one of https://github.com/google-ar/arcore-android-sdk/tree/master/samples, such as the the `computer_vision_*` one, since it extract/process camera images and renders altered images on screen), and comparing them.

Especially important to compare when and where the various ARCore APIs are called.

If you can't get your app to work, try instead starting with the working SDK sample, slowly modifying to more and more resemble your desired app. Test along the way.

**Comment by abhishekk06** [comment]
Hi @fredsa ,

I do set session.setCameraTextureName as 0 but I see a black screen and the following error in my logger.

"Invalid ray produced by view data!"
