### ISSUE TITLE
Why Google ARCore rendering uses Open GL 2.0

### ISSUE THREAD

**Issue by RajkumarRepo** [google-ar/arcore-android-sdk#127]
Normally , Open Gl is used for render the 3D object in SurfaceView. The OpenGL release 3.1 for API level 21 and above  and ARCORE the starting level API is 24 and above then why AR CORE uses Open GL Es 2.0

**Comment by SimonScholl** [comment]
So first at all there is a difference between OpenGL and OpenGL ES Versioning. I recommend https://en.wikipedia.org/wiki/OpenGL_ES#OpenGL_ES_2.0. In Short OpenGL ES 2.0 is another specification and uses a subset of OpenGL 3.3. Of course there is a newer version OpenGL ES 3.0, which adds additional, but specific functionality. Anyway this version is backward compatible with OpenGL ES 2.0.

So for basic rendering it should be sufficient to use the rendering pipeling of OpenGL ES 2.0, but i think it should be no problem to code the rendering yourself. Hope i could help you somehow.

**Comment by RajkumarRepo** [comment]
I'm asking about only Open GLES 3.2 is there but Google AR uses GLES20. In Future they uses android version of OpeGLES or not. Because OpenGLES  3.0 multiple texture rendering texturing compression. That's way I'm asking.

**Comment by inio** [comment]
While API 24 introduces the OpenGL ES 3.2 APIs, that does not mean every device running 24 fully supports those APIs.  Because the sample application is quite simple, the OpenGL ES 2.0 APIs are sufficient for implementation.

ARCore is compatible with OpenGL ES 2.0 - 3.x.  It is not compatible with Vulkan, as currently there is no broadly-supported way to getting access to the camera image as a texture in Vulkan.
