### ISSUE TITLE
How can i display/render a 2d image/view in ARCore

### ISSUE THREAD

**Issue by ShankarKakumani** [google-ar/arcore-android-sdk#1272]
### SPECIFIC ISSUE ENCOUNTERED
I am trying to display a 2d Image in AR. Which I can do with SceneForm using ViewRenderable. Are there any functions in ARCore, where I can render a 2d image/view?

### VERSIONS USED
- Android Studio: 4.2.2
- ARCore SDK for Android: 1.25.0
- Device manufacturer, model, and O/S: Xiaomi, POCO F1, MIUI 12

**Comment by devbridie** [comment]
ARCore does not provide any utilities for rendering models. You'll need to use a rendering library such as Filament or a community Sceneform fork, or write your own OpenGL.

**Comment by bounty-torn** [comment]
@devbridie, man, this question has been asked so many times (by myself and others), including at I/O this year during the ARCore AMA. It would be SUPER cool if you guys could put together some kind of library that would replicate the ViewRenderable function in Sceneform. A lot of us that are experimenting with XR are non-devs and this would GREATLY help us better contribute to the community (instead of asking this same question over and over).

**Comment by devbridie** [comment]
I completely understand where you're coming from; writing OpenGL or interacting with a rendering library is really hard if it's something you're not used to. However, something like that is a road we've already explored (Sceneform). For what it's worth, some great community forks of Sceneform are out there keeping the spirit alive, though I can't recommend one specific one.
