### ISSUE TITLE
How to add animations to agumented face? 

### ISSUE THREAD

**Issue by kyung645** [google-ar/arcore-android-sdk#1343]
On the https://developers.google.com/ar/develop/java/augmented-faces page, the demo video with the three people show animation effects like snowing or sweating on sunny day. But there is no documentation about how to add these kinds of animations? Would you happen to have any suggestions on how to accomplish animation effects as seen in that demo video/gif on the augmented face page? Thanks so much.

**Comment by devbridie** [comment]
ARCore doesn't provide any utilities for displaying or otherwise rendering of AR content, so you would have to use 3d rendering software to accomplish an effect like this like OpenGL or use an open-source library that supports this kind of thing (e.g. [a fork of sceneform](https://github.com/SceneView/sceneform-android)). The snowing and sun effects seem to be a transparent plane in front of the face with an animated texture.
