### ISSUE TITLE
Documentation not clear, need clarifications

### ISSUE THREAD

**Issue by brianm-sra** [google-ar/arcore-android-sdk#1344]
@devbridie : I had a couple of questions on things that were not completely clear from reading the documentation online.  Can you please either reply to these questions, and/or update the documentation?

(1) https://stackoverflow.com/questions/70854520/arcore-ndk-api-questions

(2) https://stackoverflow.com/questions/70886882/arcore-poses-coordinates-and-raw-depth-api-android-ndk

Thanks in advance for any clarification you can provide on those issues.

**Comment by devbridie** [comment]
Sorry for the delay on taking this up. As Michael mentioned on the question, indeed, the position of an element in the point cloud buffer is important. For example, point number 15 has coordinates `(point_cloud_data[14*4], point_cloud_data[14*4+1]. point_cloud_data[14*4+2])`, where `point_cloud_data` is the result of [`ArPointCloud_getData`](https://developers.google.com/ar/reference/c/group/ar-point-cloud#arpointcloud_getdata). The ID of this point is the 15th entry of the point cloud ID array, i.e. `point_ids[14]`.

There isn't a way to construct an ArPoint given an ArPointCloud; ArPoints come from `hitTest`'s [`ArHitResult_acquireTrackable`](https://developers.google.com/ar/reference/c/group/ar-hit-result#arhitresult_acquiretrackable).

> Question: How can a unique identifier (point id) be used to get the X, Y, Z, confidence level for a single unique point ?

Something like this:

* Iterate over `0.. ArPointCloud_getNumberOfPoints`,
* Find index of interest in `ArPointCloud_getPointIds`,
* Use index to lookup values in `ArPointCloud_getData`.

> Is it possible for an app to use the ARCore Raw Depth API (for Android device; app developed in C++/NDK or Java or Unity) to capture depths from multiple frames and combine them in memory to form a 3D map of a scene

Yes! Check out the [`raw_depth_java`](https://github.com/google-ar/arcore-android-sdk/tree/master/samples/raw_depth_java) sample. It does what you're mentioning. You're right that coordinate systems shouldn't be compared from frame to frame, and that's why the sample [creates a stable anchor](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/raw_depth_java/app/src/main/java/com/google/ar/core/examples/java/rawdepth/DepthData.java#L80) and measures coordinates relative to the stable anchor.
