### ISSUE TITLE
How to display a 3D mesh based on a .ply file (or .obj file) ?

### ISSUE THREAD

**Issue by agGitHub** [google-ar/arcore-android-sdk#1368]
Hi,

I have a .ply file that describes a 3D surface (mesh).

This .ply file is updated with new triangles at every frame.

How can I display this 3D mesh using openGL in ARCore ? I want to have semi transparent triangles with colored lines for the triangles. How to update the displayed mesh at every frame ? (it seems that onSurfaceCreated is launched only one time at the beginning of the AR Session)

I see in the helloAR app that there are renderers to display .obj files + associated png texture. So, I could also use this renderer to render my 3D .obj file. But I don't want to display the texture of the .obj file, I just want to display a colored mesh. The other problem is that I don't know if it is possible to load a new .obj at each frame when new triangles have been added to .obj file (same question as for the .ply in the previous paragraph) 

Thanks for your help !

**Comment by devbridie** [comment]
This is rather fiddly to do with samplerender, but here's a best approximation of what you could do:

> The other problem is that I don't know if it is possible to load a new .obj at each frame when new triangles have been added to .obj file

You can write to the GL context as long as you're in a GL thread. In samplerender, that's either in onSurfaceCreated or in onDrawFrame. That means you would be able to load your mesh in onDrawFrame, though be sure to profile the performance hit if you're doing it too often. If you know all of the meshes in advance, you could load them all in onSurfaceCreated and swap out which mesh is being used to render [here](https://github.com/google-ar/arcore-android-sdk/blob/e271aa3304afae21a1f64a1e2e5bd82ee44d49e3/samples/hello_ar_kotlin/app/src/main/java/com/google/ar/core/examples/kotlin/helloar/HelloArRenderer.kt#L407). 

> I want to have semi transparent triangles with colored lines for the triangles.

You'd need to [write a fragment shader](https://learnopengl.com/Getting-started/Shaders) that can render a wireframe and appropriately colors your object's faces. Probably you'd use [Barycentric Coordinates](https://www.scratchapixel.com/lessons/3d-basic-rendering/ray-tracing-rendering-a-triangle/barycentric-coordinates) to determine the distance to the edge of the triangle, and use your "wireframe" color, and otherwise the semi-transparent fill color.

Hope this helps a little, though I'll close this for not being related to the ARCore SDK.
