### ISSUE TITLE
Device calibration unavailable

### ISSUE THREAD

**Issue by ArthurSav** [google-ar/arcore-android-sdk#14]
I have galaxy s8+(G955F) and i get this message "Device calibration unavailable".
What exactly is lacking from the other s8 devices?

**Comment by xiazdong** [comment]
You can see SupportedDevices.deviceCalibrationAvailable()

**Comment by jguomoto** [comment]
@ArthurSav Your device's SKU is not on the [supported device list](https://developers.google.com/ar/discover/). We only support certain SKUs of Galaxy devices.

**Comment by elipschutz** [comment]
Can you please explain the reasoning behind this? In my case my S8+ has identical hardware to one of the supported devices, the only difference being the screen size.

**Comment by ArthurSav** [comment]
Well what do you know, someone stripped the device check and it works.
https://github.com/tomthecarrot/arcore-for-all

**Comment by jguomoto** [comment]
I just wanted to mention that you may encounter drastic motion tracking quality degrading if you run ARCore on currently unsupported device.

**Comment by janerivi** [comment]
I used th arcore-for-all and .. it works, but with frequent catastrophic drift of planes/anchors. If I don't continously observe the same area where the anchor or plane was registered and at similar angle it tends to be unstable and you will frequently see that the anchors or planes slides away form you. I would assume an employe at google could fix this for S8+ by spending a few minutes settings a handful of parameters for camera lens distortion of S8+ that may differ slightly from the supported S8. And then Google could add it to the list of supported devices... Why not add support for different devices incrementally instead of postponing to the official 1.0 launch?

**Comment by inio** [comment]
Duplicate of #89

**Comment by aakhans** [comment]
i am still getting Device calibration unavailable on my S8+,
when i look into the code it turns out that my build.fingerprint is samsung/dream2ltexx/dream2lte:7.0/NRD90M/G955FXXU1AQJ5:user/release-keys which is some thing not expected by HellorAR code, it should be some thing containing dreamqlteue ?? when we suppose to get an update build for that

**Comment by inio** [comment]
That is rather odd.  I see "samsung/dream2ltexx/dream2lte:7" in our calibration database prior to the DP2 branch.  Are you sure you're using DP2?
