### ISSUE TITLE
Would it be possible to expose the screen to world method used in hitTest

### ISSUE THREAD

**Issue by Huolju** [google-ar/arcore-android-sdk#147]
I am trying to do a manual ray cast to a plane and I end up having a really small offset.

It would be great to have a method Pose rayPose(float xPx, float yPx) to get the position and orientation of the matching world point.

Thanks!

**Comment by inio** [comment]
It's basically like this:

convert screen point to a point in clip space (x,y in [-1,1], z = some constant, w = 1), lets call it `p_clip`
also take the origin, (0,0,0,1), call it `p_camera`
compute the matrix `M = inverse(view matrix) * inverse(proj matrix)`

the tapped point should map to the ray from `M * p_camera` towards `M * p_clip`

All of the matrix\*matrix and matrix\*vector multiplies can be done by [android.opengl.Matrix](https://developer.android.com/reference/android/opengl/Matrix.html).

**Comment by Huolju** [comment]
I tried this at the really beginning but the Ray origin was still not really at the right position so the hit was really close but not exactly the same.

But I found some code [here](https://github.com/googlecreativelab/ar-drawing-java) from people at google and so I guess the magic number .125f.

I just think it would be a nice addition whatever the reason you need to exactly know the origin of a Ray on a tap on the screen rather than playing a guessing game :)

Thanks for your answer!

**Comment by claywilkinson** [comment]
Thanks again for the feedback. At this time, I would not expect this API to be added in the foreseeable future. The "magic" number is the z coordinate of the screen tap.  Since the motion event is in 2D, there is no z  value.  There are couple strategies used to get this value other than guessing, and the best approach is the one that gives you the best result in your application :) 
1. Pick a number between 0 and 1 (for example .5 or .125) usually you want to have the effect of the origin being in front of the camera position.
2. Use glReadPixels to read a pixel on the depth buffer of the mouse click.

You may also want to evaluate if [Sceneform](https://developers.google.com/ar/develop/java/sceneform/) to see if that meets your needs.  Sceneform has a high level node based scene graph which handles a lot of operations like [screenPointToRay()](https://developers.google.com/ar/reference/java/com/google/ar/sceneform/Camera#screenPointToRay(float,%20float)).

**Comment by Huolju** [comment]
Thanks for the feedback, we are indeed going to use Sceneform in a really near future. Have a nice one!

**Comment by softlion** [comment]
> It's basically like this:
> 
> convert screen point to a point in clip space (x,y in [-1,1], z = some constant (maybe -0.5?), w = 1), lets call it `p_clip`
> also take the origin, (0,0,0,1), call it `p_camera`
> compute the matrix `M = inverse(view matrix) * inverse(proj matrix)`
> 
> the tapped point should map to the ray from `M * p_camera` towards `M * p_clip`
> 
> All of the matrix*matrix and matrix*vector multiplies can be done by [android.opengl.Matrix](https://developer.android.com/reference/android/opengl/Matrix.html).

Hello,
I tried exactly that but was unable to get correct values for the resulting 3d point (M * p_clip).  
The resulting 3d coordinates are in meters, and they seem to be in a correct range.  
But they don't change much based on the screen point. I also tried directly with the extremum points in clip space with the same result.

I'm only trying to get the https://developer.apple.com/documentation/scenekit/scnscenerenderer/1522631-unprojectpoint working. I'm not using the hittest methods because of specific requirements that give better results on iOS.

The strangest part is that i'm able to draw 3D points at their correct place using (proj matrix) * (view matrix).
