### ISSUE TITLE
Geospatial API not working since today - Error Earth.State

### ISSUE THREAD

**Issue by xSabrina** [google-ar/arcore-android-sdk#1566]
Since today (a few hours ago) the Geospatial API (including your sample) suddenly stopped working.

It keeps returning ERROR_INTERNAL when checking the Earth.State (this one: https://developers.google.com/ar/reference/java/com/google/ar/core/Earth.EarthState#error_internal).

There is no other error logs besides this one. The sample asks on the UI to check for valid authentication for the API but my key did not change.

Is there something wrong with the service? I could not find any hints on services status online.

Thanks in advance!

**Comment by xSabrina** [comment]
Appearantly the service is working again.

**Comment by iqbalhassan-021** [comment]
its not working again

**Comment by xSabrina** [comment]
The same issue randomly occured again - it's not working since a few hours at least.

**Comment by rohanbhatia56** [comment]
I am getting the same error on iOS
![WhatsApp Image 2023-07-05 at 17 34 24](https://github.com/google-ar/arcore-android-sdk/assets/5320806/5cfe5568-ef95-4c92-836b-54b5075b7a1e)

**Comment by chiangandy** [comment]
next debuging task...
I use remote debugging via usb connect to device and dump log. I saw is something can answer my issues...
`11-03 16:12:12.387  5165  5196 I Unity   : Using session configuration 0x1
11-03 16:12:12.387  5165  5196 I Unity   : 	Requested Features: World Facing Camera, Rotation and Orientation, Plane Tracking, Auto-Focus, Light Estimation (Ambient Intensity), Raycast
11-03 16:12:12.387  5165  5196 I Unity   : 	Supported Features: World Facing Camera, Rotation and Orientation, Plane Tracking, Auto-Focus, Light Estimation (Ambient Intensity), Raycast
11-03 16:12:12.387  5165  5196 I Unity   : 	Requested features not satisfied: (None)
11-03 16:12:12.387  5165  5196 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
11-03 16:12:12.387  5165  5196 I Unity   : UnityEngine.Logger:Log(LogType, Object)
11-03 16:12:12.387  5165  5196 I Unity   : UnityEngine.Debug:Log(Object)
11-03 16:12:12.387  5165  5196 I Unity   : UnityEngine.XR.ARSubsystems.XRSessionSubsystem:DebugPrintConfigurationChange(Configuration, Feature) (at /Users/andychiang/unity_projects/try2/Library/PackageCache/com.unity.xr.arsubsystems@4.2.9/Runtime/SessionSubsystem/XRSessionSubsystem.cs:165)
11-03 16:12:12.387  5165  5196 I Unity   : UnityEngine.XR.ARSubsystems.XRSessionSubsystem:Update(XRSessionUpdateParams) (at /Users/andychiang/unity_projects/try2/Library/PackageCache/com.unity.xr.arsubsystems@4.2.9/Runtime/SessionSubsystem/XRSessionSubsystem.cs:128)
11-03 16:12:12.387  5165  5196 I Unity   : UnityEngine.XR.ARFoundation.ARSession:Update() (at
11-03 16:12:13.410  5165  5196 I Unity   : VPS Availability at (24.9934, 121.503): ErrorNotAuthorized
11-03 16:12:13.410  5165  5196 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
11-03 16:12:13.410  5165  5196 I Unity   : UnityEngine.Logger:LogFormat(LogType, String, Object[])
11-03 16:12:13.410  5165  5196 I Unity   : UnityEngine.Debug:LogFormat(String, Object[])
11-03 16:12:13.410  5165  5196 I Unity   : Google.XR.ARCoreExtensions.Samples.Geospatial.<AvailabilityCheck>d__93:MoveNext() (at /Users/andychiang/unity_projects/try2/Assets/Samples/ARCore Extensions/1.40.0/Geospatial Sample/Scripts/GeospatialController.cs:1331)
11-03 16:12:13.410  5165  5196 I Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at /home/bokken/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)
11-03 16:12:13.410  5165  5196 I Unity   : ` 

according to log, it mention "VPS Availability at (24.9934, 121.503): ErrorNotAuthorized". However, my keystore configure corrected which cannot find any issue. otherwise, Is that mean location (24.9934, 121.503) is not authorized to use VPS?

the log data is attached, please please help me to check this... Thanks

[debug.log](https://github.com/google-ar/arcore-android-sdk/files/13248084/debug.log)

**Comment by chiangandy** [comment]
next case, I just change some code in string content and rebuild it. App can lunch success?! 

I also check log from my device....

11-03 17:03:06.873 27356 27389 I Unity   : Using session configuration 0x1
11-03 17:03:06.873 27356 27389 I Unity   : 	Requested Features: World Facing Camera, Rotation and Orientation, Plane Tracking, Auto-Focus, Light Estimation (Ambient Intensity), Raycast
11-03 17:03:06.873 27356 27389 I Unity   : 	Supported Features: World Facing Camera, Rotation and Orientation, Plane Tracking, Auto-Focus, Light Estimation (Ambient Intensity), Raycast
11-03 17:03:06.873 27356 27389 I Unity   : 	Requested features not satisfied: (None)
11-03 17:03:06.873 27356 27389 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
11-03 17:03:06.873 27356 27389 I Unity   : UnityEngine.Logger:Log(LogType, Object)
11-03 17:03:06.873 27356 27389 I Unity   : UnityEngine.Debug:Log(Object)
11-03 17:03:06.873 27356 27389 I Unity   : UnityEngine.XR.ARSubsystems.XRSessionSubsystem:DebugPrintConfigurationChange(Configuration, Feature) (at /Users/andychiang/unity_projects/try2/Library/PackageCache/com.unity.xr.arsubsystems@4.2.9/Runtime/SessionSubsystem/XRSessionSubsystem.cs:165)
11-03 17:03:06.873 27356 27389 I Unity   : UnityEngine.XR.ARSubsystems.XRSessionSubsystem:Update(XRSessionUpdateParams) (at /Users/andychiang/unity_projects/try2/Library/PackageCache/com.unity.xr.arsubsystems@4.2.9/Runtime/SessionSubsystem/XRSessionSubsystem.cs:128)
11-03 17:03:06.873 27356 27389 I Unity   : UnityEngine.XR.ARFoundation.ARSession:Update() (at
11-03 17:03:07.690 27356 27389 I Unity   : VPS Availability at (24.99385, 121.5035): Available
11-03 17:03:07.690 27356 27389 I Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
11-03 17:03:07.690 27356 27389 I Unity   : UnityEngine.Logger:LogFormat(LogType, String, Object[])
11-03 17:03:07.690 27356 27389 I Unity   : UnityEngine.Debug:LogFormat(String, Object[])
11-03 17:03:07.690 27356 27389 I Unity   : Google.XR.ARCoreExtensions.Samples.Geospatial.<AvailabilityCheck>d__93:MoveNext() (at /Users/andychiang/unity_projects/try2/Assets/Samples/ARCore Extensions/1.40.0/Geospatial Sample/Scripts/GeospatialController.cs:1331)
11-03 17:03:07.690 27356 27389 I Unity   : UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at /home/bokken/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17)

according to log content, it mention "VPS Availability at (24.99385, 121.5035): Available". the location longitude and latitude is same as last case, but this time is avaliable! How come?! why?!

[debug_ok.log](https://github.com/google-ar/arcore-android-sdk/files/13248443/debug_ok.log)


AR service is playing game with me?

So sad...
