### ISSUE TITLE
Samsung S7 SM-G930F cannot run ARCore

### ISSUE THREAD

**Issue by YMonnier** [google-ar/arcore-android-sdk#207]
Cannot open and see ARCore app installed (via PlayStore & DDL) on my Samsung S7 SM-G930F.

**Comment by inio** [comment]
Not quite sure what your issue is.

If your issue is "I installed ARCore, but I can't find it in the launcher.":

ARCore is a service used by other applications.  There's no reason to install it directly unless required by another application.

If your issue is "I installed ARCore and built HelloAR but it's not running.":

1. What's your device fingerprint?  You can get it by running `adb shell getprop ro.build.fingerprint`
2. Please capture a logcat including the exception being thrown and any messages for at least a few seconds leading up to that.

**Comment by YMonnier** [comment]
Ok, I saw this ticket: https://github.com/google-ar/arcore-android-sdk/issues/85
Sorry for my misunderstanding.
