### ISSUE TITLE
Multiple apk for ARCore supported devices and non supported devices

### ISSUE THREAD

**Issue by rramprasad** [google-ar/arcore-android-sdk#213]
Is it possible to release multiple apk on Google play using ARCore? For example,
1) If device supports ARCore,play store install "ARCore version of app"
2) Otherwise play store install "Normal app"
is it possible to do now? Because I am trying to release two separate apk for ARCore supported devices and non supported devices.
In Unity,we can't use both Vuforia and ARCore at runtime.That's why I try to split apk.

**Comment by inio** [comment]
Yes.  Because we use the android.hardware.camera.ar feature flag in AR-Required apps, you can use this feature flag with the Play store's [Multiple APK Support](https://developer.android.com/google/play/publishing/multiple-apks.html).  Just make sure the version code of your AR builds are always higher than the non-AR build.

Alternately, just [make your application AR-Optional](https://developers.google.com/ar/develop/java/enable-arcore#manifest) and distribute a single APK to all devices.  Right now this adds around 1MB to your APK size, but we think we can reduce that pretty substantially in the next release.

**Comment by rramprasad** [comment]
Good.Thanks @inio I need to add ARScreen as a part of my app.So I need to export code from unity and copy paste the assets and libs in my project. While using both Vuforia and ARCore,I am not able to merge both assets. Thats why I plan to release two different apk,with two different Assets.So I think multiple apk(first option) is Good.

**Comment by rramprasad** [comment]
I tried to develop with Native Android OpenGL. After MultiApk support by ARCore 1.0,I start to develop on Unity.Thank you.
