### ISSUE TITLE
Does not work on flat surfaces?

### ISSUE THREAD

**Issue by jaredsburrows** [google-ar/arcore-android-sdk#24]
I have tried numerous times to get it to work on my flat kitchen counter but it seems to believe that the sink is flat.

Photos taken on my Google Pixel running Android 8.

Here are some example images:
![screen1504466846](https://user-images.githubusercontent.com/1739848/30006029-522ac6e4-90a4-11e7-81a6-6bed00b1f0df.png)
![screen1504467155](https://user-images.githubusercontent.com/1739848/30006032-522b9970-90a4-11e7-82cd-2716082b72c4.png)
![screen1504467127](https://user-images.githubusercontent.com/1739848/30006033-522bdd72-90a4-11e7-8008-ed06a97973c7.png)
![screen1504467119](https://user-images.githubusercontent.com/1739848/30006034-522cbbc0-90a4-11e7-9647-91d0d15cbaaf.png)
![screen1504467101](https://user-images.githubusercontent.com/1739848/30006030-522b39ee-90a4-11e7-9c3f-df1e2ae78eee.png)
![screen1504467078](https://user-images.githubusercontent.com/1739848/30006031-522b7a58-90a4-11e7-9797-14e6acd42545.png)

**Comment by nathanmartz** [comment]
This is roughly the expected behavior. The plane fitting code finds major planes using the feature points available. There flat texture of the countertop and sink mean that there are relatively few good feature points available, hence these results. You can see how the results change if you put some dishes in the sink, books on the countertop, etc.

**Comment by inio** [comment]
To add to @nathanmartz 's comment, you can see very few blue dots (point cloud points) on the countertop surface.  Without visual features the plane detection algorithm has nothing to work with.  No blue dots, no planes.

**Comment by jaredsburrows** [comment]
Thanks
