### ISSUE TITLE
Texture/Frame buffer failed to delete

### ISSUE THREAD

**Issue by PsycoTodd** [google-ar/arcore-android-sdk#243]
Hope if some experts encounter similar issues and can offer helps.

I get the GLSurfaceView by
mSurfaceView = getActivity().findViewById(R.id.surfaceview);

and I put GL related calls on it by mSurfaceView.queueEvent(new Runnable()...)

However, I notice that if I print out the TextureID after glGenTextures(1, &id), the ID keeps increasing even the deletion has been called. my GL calls are in CPP.

However, if I use a general opengl setting, it seems not happen and I can reuse the id from the textures which I released.

Seems like I failed to delete the textures. If it is related to the context, how could I make sure the gl resource is indeed released?

Thank you!

**Comment by thomasflynn** [comment]
each chipset driver is a bit different with how they decide to go about generating texture ids (some start at 1 and increment, some start at a large number and decrement, some reuse ids, some don't).  What you can do is try a glGetError() after your glDeleteTextures() and see if an error is reported.

**Comment by PsycoTodd** [comment]
Thanks for reply thomas, The issue is that I have two opengl implementation runs in the same device Google Pixel, it shows these different patterns. And the one with increasing ids will crash with gsl_memory_alloc fail.

**Comment by inio** [comment]
When using ARCore, there is no reason to create multiple texture for the background image.  As soon as you call `Session.update()`, the previous texture is invalidated.

ARCore's camera texture is built on [SurfaceTexture](https://developer.android.com/reference/android/graphics/SurfaceTexture.html).  Changing texture bindings incurs a call to `detachFromGLContext` and:

> The OpenGL ES texture object will be deleted as a result of this call.

Now, on the other hand if your question is unrelated to the camera texture, this seems like a general OpenGL question and should be taken to StackOverflow or similar instead of here.
