### ISSUE TITLE
Request for ARCore roadmap

### ISSUE THREAD

**Issue by alexeypodolian** [google-ar/arcore-android-sdk#27]
Will you create some kind of roadmap for ARCore ?

**Comment by nathanmartz** [comment]
What kind of information would be most useful to you in a roadmap?

**Comment by alexeypodolian** [comment]
I guess that it would be cool to have a few section.
A list of features that you are working on and a list of features that you are going to add in a near future.
Also it would be cool to have some information about release dates (e.i. when developers will be able to use ARCore in production applications). 
Thanks in advance :)

**Comment by freezeepopprice** [comment]
I've tried things out on a pixel device. Would love to know when new devices are being added. LG G6 is my development device

**Comment by dylanbaxter** [comment]
+1 for G6 support. 
Take pity on developers that couldn't afford a Pixel or Galaxy 😀

**Comment by d-tan** [comment]
I'm hoping that they also support the S8 plus. I found out shortly after I bought it that it was not supported :(  . Really would like to know what devices will be supported next.

**Comment by IARI** [comment]
I would love to see a roadmap.

Is anything like Marker-Tracking (ArToolkit) or even model tracking (VisionLib) planned?

**Comment by grozensmith** [comment]
Markers and objects are definitely important in AR! I would be interested to hear what types of use cases you're imagining for either the marker tracking or the model tracking components. Anything in particular you would want to use those features for? Anything you like/dislike about similar APIs?

**Comment by IARI** [comment]
**Use Case:** E-Learning with AR
I want to be able to develop a AR application that teaches information about systems which are comprised of multiple components each of which have their own location within the system.
For example:
- a single Device that has multiple components - i.E. a car, or a coffee machine
- stages in an assembly line
- a system comprised multiple mobile devices (which may be not stationary)

For each of these scenarios, in order to associate system components with their respective location, it would be desirable to be able to use marker- or model tracking.
Model tracking might be suitable, if it is feasible to obtain suitable models (i.e. of the complete system, if its components are stationary (i.e. car) or single components respectively).
Otherwise it is good to be able to support placing and recognizing markers (i.e. aruco markers).

Whenever a single component is recognized, the application may show an icon that allows the user to obtain information about the component (purpose/usage etc.).

**Problems with existing API's:**
- Setup: I've wasted days to get ArToolkit to run. It would be nice if something worked just out of the box.
- Support: ArToolkit 6 does not support Windows for developement. The state of release for ArToolkit 6 isn't clear to me either. Also theres broken links in the documentation.
- Tracking: the marker tracking with ArToolkit 5 is rather unstable/shaky. From what I've seen Vuforia seems to have a more stable tracking, but the stabilization seems to have the tracked object "lag" when the device is in motion.
- The beta of **Visionlib** so far supports model tracking only. It would be nice to have a stable and well maintained API with good documentation and platform integration that supports both marker- and model tracking well.

**Comment by grozensmith** [comment]
@IARI This all makes sense. Is it clear how you would use something like markers in concert with 3D objects for which you don't have 3D models? How would a marker really work with a car or coffee machine?

P.S. Sorry to take so long to respond. I read it a while ago, but didn't write back until today!

**Comment by IARI** [comment]
Probably for a car or coffee machine you would prefer to have a model.
However I can still imagine a particular model of some product which is only exhibited for training purposes on which you would just put markers.
In a factory setting, where markers could be pinned on multiple locations, that would be more interesting.

**Comment by inio** [comment]
(replying to the original question)

With the release of Developer Preview 2, we've gotten much closer to what we
hope to ship as ARCore 1.0.  We're hard at work to support 100M devices with the
launch of ARCore (coming out of preview) in the coming months.

We can't promise any specific features for 1.0 or beyond at this time, but we're
hard at work on exciting stuff, so keep your eyes out for announcements throughout 2018.

**Comment by chucknology** [comment]
A schedule with milestones would be a good roadmap.

**Comment by fredsa** [comment]
An up to date list of ARCore Supported Devices can be found here:
[developers.google.com/ar/discover#supported_devices](//developers.google.com/ar/discover#supported_devices)

**Comment by inio** [comment]
@haroldmthyng We have two open FRs in this area.  Subscribe to them for updates when there are any announced.

#94: general relocalization to a previously built map (akin to Tango ADFs)
#523: Extend time limit on cloud anchors

**Comment by fredsa** [comment]
The best place to regularly checkin for ARCore updates is currently on the [Google AR and VR](https://www.blog.google/products/google-ar-vr/) blog.

If you prefer messages pushed to your inbox, there's also a [Google VR/AR Developer Newsletter](https://services.google.com/fb/forms/vr-ar-developer-newsletter/).


As mentioned above, an up to date list of supported devices is maintained here:
developers.google.com/ar/discover#supported_devices

**Comment by richardrevesz** [comment]
It would be very nice to see if (and when) object tracking, body tacking and occlusion is on the roadmap.
Also, the work in progress developments to see what to expect.
Unity integration would also be very informative, but I assume that's up to Unity to provide.

**Comment by IARI** [comment]
The company i worked for more or less dropped the AR topic in 2018/2109 - I now work at a startup where we heavily rely on Facetracking.
So again, i turn to this issue, to realize:
It was closed, what we have is a link to the page https://www.blog.google/products/google-ar-vr/ ... 
However, a blog is simply not a roadmap: there is no info that i can plan with.

I don't want to come across like i just want to complain, but I have to say, the general situation disappoints me a bit.
The whole face tracking stuff is bad enough when compared to apple and their TrueDepth Camera...
But why can I not even find a demo app for ARCore Augmented Faces on the app store?
Am I supposed to assume that it simply is too bad to stand any comparisons with something like OpenCV?
