### ISSUE TITLE
Using ArFrame_acquireCameraImage forces API 24

### ISSUE THREAD

**Issue by eddielong** [google-ar/arcore-android-sdk#283]
My app/SDK requires optional AR (as per docs: https://developers.google.com/ar/develop/java/enable-arcore) and is set to API level 19. 
I'm using the C API and would like to be able to migrate from the GPU download to the more direct and efficient CPU access to do various things with the camera frame such as CV.

All the ARCore C APIs work fine but they return a AImage reference. The AImage APIs are only available on API 24, breaking the optional AR option. See: https://developer.android.com/ndk/guides/stable_apis.html

Is it possible to make similar C APIs for the ARImage to avoid having to use AImage?

**Comment by inio** [comment]
To do this you'll need to split your app into multiple .so files and only load the ones that use the NDK camera APIs on ≥24.  ARCore only works on API ≥24 though so that won't restrict when you can use ARCore.  As of 1.1 we actually do the same thing internally.

This is unavoidable with the way native code works on Android.

**Comment by eddielong** [comment]
Ok - that's a shame brings in more infrastructure that I'd like but no option here I suppose.

**Comment by inio** [comment]
Yeah, it's unfortunate.  I'll see if we can do something to improve this.  Maybe have sample code with a library that just wraps all the NDK camera APIs with an indirection layer so that
