### ISSUE TITLE
AR Core for Motorola G5S plus phone 

### ISSUE THREAD

**Issue by abpavani** [google-ar/arcore-android-sdk#381]
I have been keeping a watch on the blog to see when 100% rollout of the version 1.2 of the car core would be done . Finally I see it mentioned on the blog that AR Core is released and now supports the following devices . So when I logged into the play store it says "This app is not compatible with your device". I would like to know if Moto G5S Plus is supported now ? If not then when can I expect the device to be compatible with ARCore?

**Comment by duncan088** [comment]
I tried with a g5 plus, yes i know that it´snt the same device but all apps give the same error ,"encountered a problem connecting"

**Comment by inio** [comment]
@abpavani The just-refreshed supported devices page now lists "Moto G5S Plus".  If you are still having problems seeing the ARCore app on Play Store please let me know.

**Comment by abpavani** [comment]
@inio I still get a message on play store which says "Your device isn't compatible with this version". Any suggestions on what I should be doing ?

**Comment by inio** [comment]
After ... well, let's call it "a surprising amount" of digging, it seems the issue here is somewhat out of our control.  Offering ARCore for the g5s **through Play Store** is not feasible at this.  We're working on a solution, but it might be a bit.

However, the device **is compatible**.  You can download the APK from [our releases page](https://github.com/google-ar/arcore-android-sdk/releases) and install it.  However, You won't be able to download some/most/all (not sure) AR-Required apps from the Play Store until the issue is fixed.

**Comment by tomaken** [comment]
I found "moto g5s plus" was removed form the list of ARCore compatible device today.
Unfortunately I already ordered some amount of it since I believed that information which was shown in following website until yesterday.
https://developers.google.com/ar/discover/supported-devices
I hope moto g5s plus will be supported immediately.

**Comment by JamesR48** [comment]
I downloaded the ARCore apk from Aptoide and it works like a charm

**Comment by inio** [comment]
Good news everyone! (especially @abpavani @tomaken and @JamesR48)  the 1.2 hotfix just released enables support for the Motorola G5s+.
