### ISSUE TITLE
Could you please illustrate the PlaneRender.class?

### ISSUE THREAD

**Issue by xiaowu4** [google-ar/arcore-android-sdk#40]
Hello, I'm get ARCore backgroud by textureID and then using SurfaceTexture. And I found the picture gets from ARCore is **rotate and flip**. But the plane is right. I was wonder why the plane is right? 
And I want to change the shader, but I found the shader is something different.
Why the plane shader use (x, z, alpha)? 
I found this code in plane_vertex.shader 
**attribute vec3 a_XZPositionAlpha; // (x, z, alpha)**

**Comment by inio** [comment]
I'm slightly confused by this question as the PlaneRenderer class is for rendering detected planes in the scene, not the camera image.

The camera image can become rotated and flipped because the camera and display do not usually share an idea of "up" and "right".  use the `ArFrame.transformDisplayUvCoords` method to convert normalized screen-space coordinates to camera texture coordinates.

Planes are rendered correctly because the pose returned by `ArCamera.getDisplayOrientedPose()` (which with DP1 was called `ArFrame.getPose()` if I recall correctly) follows the logical display orientation needed for rendering of the virtual image, not the physical camera orientation.

Does that answer your question?

**Comment by inio** [comment]
Oh, and for your last question:

> Why the plane shader use (x, z, alpha)?

The alpha allows the edge of the plane to be faded.  We don't include Y because every Y coordinate would be zero.

**Comment by xiaowu4** [comment]
@inio I'm not saying PlaneRenderer is rendering camera picture. I just wonder why plane is right while camera image may be rotate. Sorry for my poor explaintaion and thanks for your help. 
About the coordinate (x, z, alpha), I still confused why every Y coordinate would be zero
