### ISSUE TITLE
arcore-preview.apk on Google Play?

### ISSUE THREAD

**Issue by lvonasek** [google-ar/arcore-android-sdk#45]
Would be possible to add ARcore dependency into Google Play so I do not have to ask users to install apk from github?

**Comment by Ernie1998** [comment]
You need to install it using adb.

**Comment by Ezorrio** [comment]
@lvonasek it's already at Google play
Check out "Tango Core"
https://play.google.com/store/apps/details?id=com.google.tango
But for now it's not available for Pixel

**Comment by lvonasek** [comment]
@Ezorrio - this APK is currently for "obsoleted" Tango devices (Lenovo Phab 2 Pro and Asus Zenfone AR). I asked if they can update it for Pixel and S8

**Comment by Ezorrio** [comment]
@lvonasek +1 for this one

**Comment by nathanmartz** [comment]
TangoCore.apk is for Tango devices only. ARCore.apk is for ARCore and will have a totally separate bundle id, Play Store listing, etc when we end the developer preview of ARCore. ARCore.apk is not in the play store right now because the preview is for developers only, but it will be on the play store for the "1.0" release, at which point ARCore will be ready for devs to use in shipping apps.

**Comment by miguelbandera** [comment]
Any date avaible for the end of the preview?
