### ISSUE TITLE
Information about normals at 3D points

### ISSUE THREAD

**Issue by DJdhruv** [google-ar/arcore-android-sdk#461]
Hi,

Once I know the 3D coordinates of a point, How can I proceed to calculate/extract the normals for the surface at that point ? Does ARCore already store information about normals ?

**Comment by SimonScholl** [comment]
I think this is not in scope of the ARCore, since you already had to calculate normals yourself with tango as well. If you are using the the C-Api i can recommend you to have a look at the point cloud library (pcl) http://pointclouds.org/

This lib includes a lot of pointcloud processing and of course normal calculation.

**Comment by DJdhruv** [comment]
Thanks a lot for your help.

**Comment by avirodov** [comment]
Hello. We compute normal estimate for some points during hit test for [oriented points](https://developers.google.com/ar/discover/concepts#oriented_points). However, this functionality is not available for any arbitrary point. Also, there are more efficient ways to go about it if you need to compute normals across multiple points, such as the library pointed out above.
