### ISSUE TITLE
How to get the normal vector of a detected plane ?

### ISSUE THREAD

**Issue by Kitwradr** [google-ar/arcore-android-sdk#462]
Basically I have a detected plane and I want to get equation of the plane so that I can map some of the points on that plane into 2D in the sense making Z values of those points same maintaining the distances between them . So getting the normal vector of the detected plane would be helpful in this process of converting 3d points to 2d

**Comment by Kitwradr** [comment]
Well I figured out how to get the normal vector of the detected plane 
Here's is the code
`DetectedPlane.CenterPose.rotation * Vector3.up;`

Now if someone can help me getting 2d points with this data :/

**Comment by avirodov** [comment]
Hi, if you want to project 3d points on a plane, you need to have a 2d coordinate system in mind. A natural one is the one defined by the global axis, but that will work well with one kind of planes (say horizontal) but not another (say vertical).

Another choice of coordinates is the one defined by CenterPose, but it can change every frame. So if you need the 2d points only for 1 frame, this is can be written as:
x_local_axis = DetectedPlane.CenterPose.rotation * Vector3.forward;
z_local_axis = DetectedPlane.CenterPose.rotation * Vector3.right;
// loop over your points
x = Vector3.Dot(your_3d_point, x_local_axis);
z = Vector3.Dot(your_3d_point, z_local_axis);

If you need a 2d coordinate system that is consistent between frames, you probably would want to attach an anchor to any plane of interest, maybe at DetectedPlane.CenterPose, and do the same math as above, but with anchor rotation instead of plane rotation. The x and z axes of the anchor will provide a 2d frame of coordinates that is consistent between frames.

Please reopen issue if this does not answer your question.

**Comment by Kitwradr** [comment]
Thanks a million for this info 👍
