### ISSUE TITLE
[Question] TextureDimension

### ISSUE THREAD

**Issue by wuzeqin** [google-ar/arcore-android-sdk#547]
I get cameraConfig 
 Zed === (imageSize:640x480| textureSize:1920x1080) 
    Zed === (imageSize:1280x720| textureSize:1920x1080) 
    Zed === (imageSize:1920x1080| textureSize:1920x1080) 
 in my OnePlus 5
Why imageSize does not equl to textureSize?
And What's difference between using ArSession_setCameraTextureName with a GL_TEXTURE_EXTERNAL_OES texture to draw and using ArImage_getNdkImage translate into GL_TEXTURE_2D texture to draw ?
I'm new arcore developer,  hope answer me , thank you very much.

**Comment by inio** [comment]
I'll answer your second question first, which I think will help with understanding the first one's answer:

> And What's difference between using ArSession_setCameraTextureName with a GL_TEXTURE_EXTERNAL_OES texture to draw and using ArImage_getNdkImage translate into GL_TEXTURE_2D texture to draw ?

With the `GL_TEXTURE_EXTERNAL_OES` approach, you get several advantages:
1. The graphics driver can use a efficient storage format like YUV 4:2:0 or other proprietary formats, allowing for reduced memory bandwidth both when writing the image into memory and when sampling it back out for the texture,
2. The graphics driver hides the [complexity](https://forums.ogre3d.org/viewtopic.php?t=25877) of any format details such as compression, chroma/luma to RGB conversion and chroma subsampling,
3. The image is written into system memory by the [ISP](https://source.android.com/devices/camera/camera3_requests_hal#hal-subsystem) (or [hardware scaler](https://android-developers.googleblog.com/2013/09/using-hardware-scaler-for-performance.html)) and read out once (by the GPU).  Those pieces are both far more power efficient at what they do than the CPU could be, and you get more free CPU time for other things,
4. Because of OpenGL's API design, `GL_TEXTURE_2D` requires at least one copy be made for each update (from the source buffer into the permanent texture storage).  While this copy is usually hardware assisted, it's still additional DRAM bandwidth and thus power and also blocks the rendering thread unless you're really sneaky with buffer objects.

> Why imageSize does not equal to textureSize?

Now, remembering that DRAM bandwidth is both a limited resource and costs power, `(imageSize:640x480| textureSize:1920x1080)` will use at about 43% less DRAM bandwidth than (imageSize:1920x1080| textureSize:1920x1080).  [With Android P this may change](https://source.android.com/devices/camera/versioning#80) but for now the CPU and GPU cannot share storage and so minimizing the CPU image size reduced memory bandwidth.

**Comment by wuzeqin** [comment]
Thank you very much for your help 👍 . I learn so much. Another problem occur to me which I get AImage （use this method - ArImage_getNdkImage）from ArImage , and get AImage Data , such as format  is YUV_420_888 , plane is 3 and so on. I serched many and I found the ArImage no NV12, no NV21, no I420.  I guess it is YUV-420-PackedSemiPlanar according to the log 
![_3f9add1f-af0a-45ef-b99a-616bdcd7c1fb](https://user-images.githubusercontent.com/9404871/45370818-9a115700-b61b-11e8-9142-040d45b913f1.png)
.  I know the first plane is Y data , the second is UV interleaved , my question is that what the third plane is .  How can I change this to NV12 or NV 21 or I420.

**Comment by wuzeqin** [comment]
hi , inio, thank you once again.   I want to ask for your help, when anthoer wired problem happen to me. In Galaxy S9 or HUAWEI Honor 10 ,when I create ARSession on the second time,it crashs.  
<img width="1633" alt="qq20180911-235021 2x" src="https://user-images.githubusercontent.com/9404871/45371572-8109a580-b61d-11e8-8f2c-c1d98919d040.png">
Please give me some suggestion , I have no idea to deal with it. Thank you @inio

**Comment by inio** [comment]
Responded to this above issues in #561

**Comment by inio** [comment]
Closing as this sounds resolved.
