### ISSUE TITLE
Crash on Session.resume() (IllegalArgumentException)

### ISSUE THREAD

**Issue by AliShug** [google-ar/arcore-android-sdk#61]
Weird crash, since the hello_ar example works for me. When attempting `Session.resume()` (occurs at application startup), an IllegalArgumentException in ObjectWrapper.class is hit (I've dived in a little based on what the decompiler is showing me):

`"The concrete class implementing IObjectWrapper must have exactly *one* declared private field for the wrapped object.  Preferably, this is an instance of the ObjectWrapper<T> class."`

I've set a breakpoint at the exception line, and there doesn't seem to be anything wrong with the object in question (`remote`?), which seems to be some kind of proxy object containing a reference `mRemote` to the actual `ObjectWrapper`, which is wrapping my `MainActivity`. The code in ObjectWrapper.class checks the number of fields (??) to validate the proxy object, and comes up with 3 fields rather than the expected 1. It's looking for a single private field, which is there, but also finds two public fields, `public static transient volatile com.android.tools.ir.runtime.IncrementalChange com.google.tango.loader.ObjectWrapper.$change` and `public static final long com.google.tango.loader.ObjectWrapper.serialVersionUID`, so it halts and erroneously throws the exception above.

**Comment by AliShug** [comment]
Switching to Gradle plugin 2.3.3 (from 3.0.0) seems to fix the problem.

**Comment by nathanmartz** [comment]
Closing as this appears to be fixed.

**Comment by dthian** [comment]
Hi @nathanmartz, from the above aforementioned comments, is there then a restriction on the Gradle and/or Android Studio version that we can use? (There doesn't seem to be any version restriction state on the [AR Getting Started](https://developers.google.com/ar/develop/java/getting-started) page.

If not, is this issue fixed on the latest Gradle plugin version (4.1)? We seem to be bumping into the same crash with the latest version and but are unable to downgrade due to certain dependencies that we have deployment pipeline. 

Much thanks!

**Comment by llDavidll** [comment]
Hi,
As commented on #87 , you can try disabling instant run.
