### ISSUE TITLE
ArImage_getNdkImage Image 90 Degrees rotate.

### ISSUE THREAD

**Issue by Canato** [google-ar/arcore-android-sdk#655]
When I'm getting the ndkImage it is coming with rotation.

this is my code:
```
 ArImage_getNdkImage(ar_image, &ndk_image);

    if (ndk_image == nullptr) {
        return;
    }
    int32_t out_format;
    AImage_getFormat(ndk_image, &out_format);
    CHECK(AIMAGE_FORMAT_YUV_420_888 == out_format);

    int32_t srcPlanes = 0;
    AImage_getNumberOfPlanes(ndk_image, &srcPlanes);
    CHECK(srcPlanes == 3);

    AImage_getPlaneData(ndk_image, 0, &input_pixels, &length);
    AImage_getPlaneRowStride(ndk_image, 0, &out_stride);
```

**The problem is:** 
I'm using library to save the Image (input_pixels/data) in the android mobile, but the image is coming turned counterclockwise.

I could rotate the image, but I"m feeling that the Pose and Intrinsics would not be valid anymore, how to I make sure that the image is right?

**Comment by inio** [comment]
The Computer Vision sample shows how to compute the rotation from camera to display:

https://github.com/google-ar/arcore-android-sdk/blob/master/samples/computervision_c/app/src/main/java/com/google/ar/core/examples/c/computervision/ComputerVisionActivity.java#L201

**Comment by EbadSyed** [comment]
@Canato Are you using OpenCV or some other library as well ?

**Comment by Canato** [comment]
@EbadSyed I'm using my own library which uses OpenCV, but this is outside my Android Project.

**Comment by inio** [comment]
@Canato Android device manufacturers are free to orient their device's cameras however they want.  Phone-form-factor devices have somewhat standardized on one orientation, but weird devices like the Nexus 5X where the camera is rotated 180° from how it's mounted on most other devices.  There's also the possibility of natively-landscape devices where the camera and display have the same natural orientation.

With 1.6 (just released) you could now look at the relative poses of `ArCamera_getPose()` (image pose) and `ArCamera_getDisplayOrientedPose()` (display pose) to determine the rotation, but the code in the computer vision sample is probably cleaner since you'd need to do your own quaternion composition to do that.

**Comment by Canato** [comment]
Yes I saw on the new release, thanks!
