### ISSUE TITLE
the picture in the camera seems to be distorted in xiaomi's mix 2s

### ISSUE THREAD

**Issue by silverbullet1472** [google-ar/arcore-android-sdk#695]
- Device manufacturer, model, and O/S: xiao mi mix2s /android:9
- ARCore: v1.5.0

the picture in the camera seems to be distorted, like the image here
<img src="https://github.com/silverbullet1472/LocationTest/blob/master/bug.png">

**Comment by fredsa** [comment]
Closing as this issue is missing key information to help us reproduce it.
- ARCore SDK version
- Device manufacturer, model, and O/S
- ARCore APK installed version:
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`
