### ISSUE TITLE
ArTrackingFailureReason reference documentation missing

### ISSUE THREAD

**Issue by ptc-dberry** [google-ar/arcore-android-sdk#739]
The enum types for ArTrackingFailureReason are not documented on the reference web site.  For example here,

https://developers.google.com/ar/reference/c/group/camera#group__camera_1gaf7dd90da7fa2a4b572156d0984a372c4

You cannot click on ArTrackingFailureReason and find out its values.  I would have expected to see the values here  https://developers.google.com/ar/reference/c/group/common for instance.

You need to look in the arcore c api header file for them.

**Comment by fredsa** [comment]
Thank for the report. We'll get this fixed.

In the mean time, here are the values:

/// Indicates expected motion tracking behavior. Always returned when
/// ArCamera_getTrackingState() is #AR_TRACKING_STATE_TRACKING. When
/// ArCamera_getTrackingState() is #AR_TRACKING_STATE_PAUSED, indicates that
/// the session is initializing normally.
AR_TRACKING_FAILURE_REASON_NONE = 0,

/// Motion tracking lost due to bad internal state. No specific user action
/// is likely to resolve this issue.
AR_TRACKING_FAILURE_REASON_BAD_STATE = 1,

/// Motion tracking lost due to poor lighting conditions. Ask the user to
/// move to a more brightly lit area.
AR_TRACKING_FAILURE_REASON_INSUFFICIENT_LIGHT = 2,

/// Motion tracking lost due to excessive motion. Ask the user to move the
/// device more slowly.
AR_TRACKING_FAILURE_REASON_EXCESSIVE_MOTION = 3,

/// Motion tracking lost due to insufficient visual features. Ask the user
/// to move to a different area and to avoid blank walls and surfaces
/// without detail.
AR_TRACKING_FAILURE_REASON_INSUFFICIENT_FEATURES = 4,

**Comment by michaelmauzy** [comment]
Thanks for your report. We have fixed the documentation for these pages:

- https://developers.google.com/ar/reference/c/group/common

- https://developers.google.com/ar/reference/c/group/camera#arcamera_gettrackingfailurereason
