### ISSUE TITLE
Debugging 

### ISSUE THREAD

**Issue by renesmee12** [google-ar/arcore-android-sdk#740]
### VERSIONS USED
- Android Studio: 
- ARCore SDK for Android: 
- Device manufacturer, model, and O/S: 
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

### STEPS TO REPRODUCE THE ISSUE
 1.
 1.
 1.

**Comment by fredsa** [comment]
Closing as this issue is missing key information to help us reproduce it.
- Unity version
- ARCore SDK for Unity version
- Device manufacturer, model, and O/S
- ARCore APK installed version:
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell pm path com.google.ar.core`
- Output of `adb shell getprop ro.build.fingerprint`

**Comment by renesmee12** [comment]
Plz give me where a can find all that plz
