### ISSUE TITLE
Information update that broke everything

### ISSUE THREAD

**Issue by Qnetis** [google-ar/arcore-android-sdk#746]
![image](https://user-images.githubusercontent.com/23212415/54778995-27ff7780-4c27-11e9-9db7-fbeca5bb2b65.png)
I bought myself a Mi Mix 2S phone specifically for arcore, I chose a long time, I collected money for a long time.  Tomorrow he will come.  I go to the mobile phone support site and bang "No support for CPU image access."
 Excuse me, is this a joke?

**Comment by lvonasek** [comment]
I do not belong to Google ARCore team, I am the developer of 3D Scanner app only. But I will answer this as Google is recently answering really small amount of reports here.

Xiaomi devices are working well together with ARCore, I do not know any single app which lacks functionality because of missing CPU image access support.

App developers can always always render the camera data from GPU to texture and copy it to CPU (which I finds easier as transferring the raw camera data to display coordinate system).

Here is some discussion about it: https://github.com/google-ar/arcore-android-sdk/issues/683

**Comment by Qnetis** [comment]
> Я не принадлежу к команде Google ARCore, я только разработчик приложения 3D Scanner. Но я отвечу на это, поскольку Google недавно отвечает на очень небольшое количество отчетов здесь.
> 
> Устройства Xiaomi хорошо работают вместе с ARCore, я не знаю ни одного приложения, которому не хватает функциональности из-за отсутствия поддержки доступа к изображениям процессора.
> 
> Разработчики приложений всегда могут визуализировать данные камеры из графического процессора в текстуру и копировать их в центральный процессор (что для меня проще, чем передавать необработанные данные камеры в систему координат отображения).
> 
> Вот некоторые обсуждения по этому поводу: [# 683](https://github.com/google-ar/arcore-android-sdk/issues/683)


Thank you very much for the answer, if it is not difficult for you to tell your thought in more detail.

**Comment by fredsa** [comment]
Duplicate #683 

Xiaomi CPU image access was fixed in the 1.8.0 release:
https://github.com/google-ar/arcore-android-sdk/releases
