### ISSUE TITLE
Is ARCore dead?

### ISSUE THREAD

**Issue by FUBAR2077** [google-ar/arcore-android-sdk#775]
Why no one is taking care of issues for like 2 months now? Either on Android SDK nor ARCore for Unity..? Why Google is treating this technology like this? 

I thinks it deserves so much more support and improvements to catch up to ARKit 2.0.

I hope that ARCore will get sufficient workforce needed..

**Comment by michaelvogt** [comment]
This is just how this team shows his attitude. It has been the same with Tango, so it is like this already for a long time. Not sure what they expect to gain from being like this. Certainly not trust in the technology. 

Lets see if there are any news during IO. Better don't hold your breath.

Regarding workforce: The numbers I heard last year have been pretty low on Google's side, compared to Apple's.

Seeing how great some open source projects from Google work, shows how wrong closed source is.
Same for Sceneform, btw.

**Comment by lvonasek** [comment]
I saw that this started after introducing Hololens 2. Does the history repeat?
-Google Tango killed because of Apple ARkit
-Google ARCore killed because of Microsoft Hololens 2

**Comment by FUBAR2077** [comment]
@michaelvogt - trust in technology is being crushed by random crashes and instabillity currently and with this first solutions created for clients rather kill this tech instead of promoting it further.. If they won't do some progress really fast this amazing tech will be dead in no time.

@Ivonasek - sure the HL2 is out but it's totally different use case and different pricing for final client - ARCore uses the device that everyone has in his pockets ant HL2 is >3000$.

**Comment by michaelvogt** [comment]
Well, with IO so close, lets see if and what they have to say there.

**Comment by mpottinger** [comment]
Yeah it is worrying, it is not atypical of google to be so wishy washy on projects, starting lots of stuff and then killing it is a well known Google thing so it has me worried.

However I'm also waiting for IO to see what is presented. There are time slots allocated to ARCore.

So they may not be killing it, lets see. The silence is eerie though.

**Comment by DavidArayan** [comment]
Issues going unanswered and complete lack of communication are never a good thing. It feels like google had to rush ARCore out the door to answer for ARKit and are paying a hefty price for it.

Having some basic communications to instil some confidence around this tech would be nice. There are people who are operating entire business ventures built around these technologies.

**Comment by mpottinger** [comment]
@DavidArayan I have read articles that it is because of the internal structure of Google, and the way promotions work, etc. It encourages a focus on the next shiny release of a new product, while existing products get neglected.

It is really affecting confidence in Google products, but the thing is, advertising is still the bulk of Google's revenue.

This worsening erosion of developer trust won't matter at all if it doesn't affect their bottom line, and right now it probably isn't, and never will, so the problem may never be solved.

**Comment by Thaina** [comment]
LoL after you have post this just a day it release 1.9.0

**Comment by FUBAR2077** [comment]
@Thaina yes ;) but like @michaelvogt mentioned - more likely it's connected to Google I/O, and good ther is 1.9.0 with continous Image Recognition so we're one step closer to ARKit :)

It would be good if this and Unity Issue board wouldn't be so dead with so many unadressed issues, but good it's not fully dead in the "inside".

**Comment by michaelvogt** [comment]
I don't think Google can afford to cancel general AR functionality on their platform. Spacial computing too important to have, so no worries here.

The problem is, that Google seemingly prioritizes their own use cases (Playground 🤦‍♂️) so far above others, especially above fixing bugs they seemingly don't care for their apps. Who on earth needs vertical planes to work, right 😒

And that they care much more to do the catch up game to check off some checkboxes, and not so much to make things work. 

Now, the changes for augmented image is very welcome. Providing a long requested feature. Hope this is only the beginning - and that it actually works

**Comment by michaelvogt** [comment]
Oh btw, the AR navigation feature in Google Maps works really well (as far as ARCore can go). So there is hope 😊

**Comment by mpottinger** [comment]
@Thaina Well, yes it is a bit of a reassurance. If there wasn't any new release though I'd be really worried.

This new release doesn't have the new features I would personally be excited about. I am personally waiting for some kind of depth/occlusion capabilities like Tango.

Right now that should be possible on some phones via hardware, and software only solutions for dense depth exist now, well, at least as research that hasn't been released.

Good to see it though anyway.

**Comment by rkoshti** [comment]
Is that possible to detect human body parts with arcore? Same as face API. Interested in human foot and finger detection. Any help will be appreciated.

**Comment by Thaina** [comment]
@rkoshti I have created #736

**Comment by FUBAR2077** [comment]
1.9.0 works more stable on my S7, previously there were random crashes so big thumbs up for performance tweaks for the ARCore team too :) 👍 

Looking through the issue boards with no answers is scary but maybe they will look in there sometime..
I can see that many issues are questions that should be at stack overflow, not as an issue, so maybe if issue count was lower, they will come in there more often.

**Comment by AlexInTheEcho** [comment]
I want to say that I can't understand about Arcore's situation is the lack of official nformation. Since October, I've been waiting to use arcore in my Redmi Note 5, and nowadays, not only my phone it's not supported, but also the Xiaomi's part in the list hasn't changed at all, and it's frustating. I've been investigating since months and I don't know what happens. And there are more cases such a stupid, smartphones that can be supported but are not for no reason

**Comment by mpottinger** [comment]
@rkoshti Not as part of the arcore sdk, no. You need a separate sdk for that. There are some out there that would use tensorflow lite. Look up tflite. You would need to feed the raw camera images from arcore to that.

**Comment by mpottinger** [comment]
@AlexInTheEcho Yes, the way google is treating this project at least outwardly is really bringing down my confidence in the platform.

Maybe it isn't as popular as Google had hoped, or they no longer see any business sense in it.

It's true there are still no really compelling ARCore apps out there.

My use case didn't involve AR games anyway. I was more using it for easy access to the mapping/localization functionality, for warehouse use.

There are other open source SLAM software I can use so I'm planning to move over to that instead.

The anchor functionality and relocalization in ARCore is second to none though and no real replacement for that in the open source world.

**Comment by michaelvogt** [comment]
Alone the fact that this discussion is happening here, and neither someone from Google joins in or even just forced closed, tells everything how little Google cares about whats written in the issues. Listening to the wonderful product managers on stage during IO saying 'we love to hear from you' is a slap in the face to everyone here.

**Comment by AlexInTheEcho** [comment]
@michaelvogt I totally agree with you. I came here, to github to search information about Arcore, hopefully official information about it, and I found that there's no information furthermore in post like this. It's so frustrating 'cause in my case I've been waiting since the launch of AR+ in pokemon go in android, and I'm fascinating with that feature, but a I can't use it. Because of Google, I don't have support, and I don't know why

**Comment by fredsa** [comment]
I would like to start by apologizing for the limited responses you may have gotten here, and in our other ARCore issue trackers recently. We're absolutely still here and continue to work on new features, as well as improvements to the underlying tracking algorithms, so that we can improve the experience for your users, and to bring ARCore capabilities to more devices. That said, we do want to improve our responsiveness in this forum, so please bare with us as we work though this process. Note that even though we're not always able to respond right away, we do look at the issues, and do very much appreciate the feedback, and especially the bug reports when something isn't working the way it should.

On a separate note, I'm glad to hear that the most recent improvements in Augmented Images are appreciated. Next up for us is shipping the features we shared early versions of at Google I/O. We're eager to see what experiences you create with them.

I'm closing this issue as I believe the original question has been addressed. Though, once again, thank you for your thoughts and feedback, as well as for taking the time to write us here.

**Comment by liho00** [comment]
I think ARCore really lags far behind ARKit. As an Android developer, I feel lucky for Apple users and I feel sad for Android users.

Post questions and questions on stackoverflow and github, no one writes back.

Have a look of ARKit 3 new features, https://developer.apple.com/augmented-reality/arkit/
![61884035_626862041162248_7287741593509953536_n](https://user-images.githubusercontent.com/34411102/58877498-66bfac80-8703-11e9-97c9-27c4ff7764b9.jpg)

I know that the ARCore team is doing their best. But, I hope Google can recruit more experts in this ARCore team.

**Comment by Thaina** [comment]
@liho00 It hardly be comparable

Because Apple manufacture it's own phone to have depth sensor specifically for AR

While google work with highly fragmented devices from selfish manufacturer who don't agree with each other. And ARCore need to be hacked to use it's own hacky technique instead of depth sensor

Maybe it's just that ARCore is actually impossible from the start. We really need depth sensor or at least dual camera. And google just overconfident that their hacky system could really be used in the real world. And turn out it's not work

**Comment by Thaina** [comment]
Well, seriously I think google should stop this useless ARCore system right now and just focused on negotiation with android phone manufacture to put some hardware for AR in the next gen phone. The depth map from camera shaking they try to hacking can only be graduated thesis. It hopelessly waste time and effort to just calibrating the device

**Comment by michaelvogt** [comment]
The little importance Tango and ARCore inside Google had and has is reflected all over the place. Google didn't build a Tango device, nor do they have better sensors for AR in the Pixel series.

They finally found a sweet spot for ARCore usage, which actually works pretty good for me, that is localisation in Google Maps. But instead of showcasing this feature during Google IO, they use augmented images, which is hardly really useful for such a use case. 

On top of missing hardware and up to date service demonstrations, the way of communication doesn't help either to gain confidence in ARCore. 

The mistakes that are creeping in the ARCore releases now and then, without showing the slightest interest to fix them as fast as possible is a perfect indicator how much they care.
