### ISSUE TITLE
Navigation at Google I/O

### ISSUE THREAD

**Issue by michaelvogt** [google-ar/arcore-android-sdk#783]
As shown during the presentation about augmented images during I/O, Google had an AR based navigation function in the IO app. It is necessary to scan an image of a physical signpost, then see markers pop up that show where for example where a stage is that you might looking for.

Now, I wonder why this is done with augmented images, as this has some clear disadvantages that renders it completely useless for real world app. One is, that to see these markers, the user first needs to find a signpost. I assume this led Google to place a staggering 50 signposts inside the event area. Many more reasons that show that using augmented images for such a feature is exactly the wrong thing to do.

Any insight why you haven't used cloud anchors for this would be very welcome. Is this how you acknowledge that they aren't fit for practical use? Localisation is working actually pretty well in Google Maps. So why not doing this the right way by mapping the event area and let users localize from any place they are directly?

**Comment by gitunit** [comment]
have you ever thought about viewing it from the organizers perspective? imo opionion utilizing those signposts is a good idea, at least for two reasons: **a)** you have a physical map for every attendee to get fast orientation on the area without any electricity or device needed and **b)** you can use it as a trigger and anchor for a 3D map, oh and there is also **c)** scanning a marker is more fail-safe. of course utilizing cloud anchors could have been done but would have been a bit of an overkill for those 3 days, imo. i guess we will see such navigations done with cloud anchors at some point but since nothing in that direction was announced at the Google I/O, it means it is not ready for the general public.

**Comment by michaelvogt** [comment]
Ok, interesting.

Let's find out what the were the reasons why Google decided to use augmented images instead of cloud anchors.

**Comment by fredsa** [comment]
There are possibly many AR experiences we could've created for Google I/O.

Cloud Anchors lets you establish a common frame of reference (shared coordinate system), so that users across different devices can participate in a shared experience. For "Explore I/O" we really only needed to align the virtual world (the Google I/O map) with the real world (the actual venue). Augmented Images allowed us to do that in a fairly straightforward way.

**Comment by michaelvogt** [comment]
And did it work out as you expected? Was it a good fit for the task, or could cloud anchors have provided a better experience?
