### ISSUE TITLE
transformCoordinates2d not working on Nexus 5X

### ISSUE THREAD

**Issue by Oyashirox** [google-ar/arcore-android-sdk#811]
### SPECIFIC ISSUE ENCOUNTERED

On Nexus 5X, calling 
```kotlin
val mappedFloat = FloatArray(4)
// Transform image pixels to view pixels
frame.transformCoordinates2d(
            Coordinates2d.IMAGE_PIXELS,
            floatArrayOf(boundingBox.left, boundingBox.top, boundingBox.right, boundingBox.bottom),
            Coordinates2d.VIEW,
            mappedFloat
)
``` 

does not put result in `mappedFloat`. It works correctly on a OnePlus 6 and Samsung S9, but not on Nexus 5X.

### VERSIONS USED
- Android Studio: 3.6 Canary 3
- ARCore SDK for Android: 1.10.0
- Device manufacturer, model, and O/S: Google, Nexus 5X, Android 8.1.0
- ARCore: 
 Packages:
      versionName=1.10.190603066
- Output of `adb shell getprop ro.build.fingerprint`: google/bullhead/bullhead:8.1.0/OPM7.181205.001/5080180:user/release-keys

**Comment by devbridie** [comment]
Sorry that we didn't respond appropriately to this bug. As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
