### ISSUE TITLE
ARCore world coordinate -z axis heading w.r.t North

### ISSUE THREAD

**Issue by therahulmeena** [google-ar/arcore-android-sdk#829]
Hi,
I am trying to draw a path using two LatLng points in AR World Coordinates. I have converted these  coordinates to world coordinates i.e. (x,y,z) using bearing & distance between them. I'm taking the initial heading of -z axis on first onUpdate method call assuming that the very first frame pose's (using getDisplayOrientedPose()) direction will be the initialized world coordinate system i.e. -z axis being in the direction of the camera facing forward. But as soon as I draw a path node using an anchor on floor & this system, the node's orientation comes out to be slightly shifted towards right or left by +-15 degrees. The conclusion was that the world coordinate system updates itself when arcore gathers more data about its surrounding. So I no longer can depend on the initial frame pose. 

So how can i get the world coordinate's -z axis alignment w.r.t north on each onUpdate method call to update my node's orientation?

**Comment by beyondny** [comment]
Hi. Maybe I have some code that you want. How can I contact you?

**Comment by therahulmeena** [comment]
> Hi. Maybe I have some code that you want. How can I contact you?

Hi, you contact me at rahul184.iitr@gmail.com. Thanks.

**Comment by thomasMend** [comment]
> Hi. Maybe I have some code that you want. How can I contact you?

Hello, I am also currently trying to solve the same issue and I was wondering if I could also get in contact with you. My email is thomas78mend@gmail.com

**Comment by jpeltone** [comment]
Hi, when I played around this earlier this was very much dependent on the phone and it's sensors, have you tried this with different phones and using different sensors (magnetometer, accelerometer, rotation vector)? Are you taking into account the geomagnetic field declination when figuring out the bearing (map north vs true north)? At least for me this had an effect when using camera.forward().

**Comment by thomasMend** [comment]
Yes, the initial azimuth and calculated bearing we receive from the phone is dependent on the phone's sensors (explains why angle might be off by about +/- 15 degrees at first even if calibrated correctly), but the problem is that AR Core's 3D coordinate system will very likely rotate and move as it tries to understand it's environment. Therefore we would need to update our assumed bearing that was used to reference the Earth's latitude and longitude, but as far as I can tell, there is nothing from ARCore's SDK we can use to check when this would happen. 

You can also clearly see that the coordinate system can rotate if you were to place an object at AR Core's vector(0, 0, 0) and at vector(0, 0, -1) and then either moved around the space with the two objects or covered the camera with your hand (completely losing tracking) and had the camera look at an unrecognized area. You would see that the -z axis is now pointing at a completely different direction when tracking is resumed, making our first bearing calculation useless. 

The only solution I can currently think of would be to predict where the ARCamera would would be in the next few frames using accelerometer data and and see if it is at the correct approximate x,y,z position and rotation. If it is not what we expected, then we can assume that the AR coordinate system is moving and rotating which makes it unreliable to use our previous calculated bearing, and we must get the most recent azimuth in order to get a new calculated bearing to relate to latitude and longitude coordinates.

**Comment by amitne7** [comment]
> Hi. Maybe I have some code that you want. How can I contact you?

Hi, i have same issue with rendering path, will you please contact me on amitnet@gmail.com

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
