### ISSUE TITLE
Why install ar-core preview apk for running hello ar core sample?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#85]
Why we need to install the ar-core preview apk in the device for running hello ar sample in android?

**Comment by inio** [comment]
ARCore requires a large amount of algorithmic code to operate.  Instead of bundling this into every application, we distribute a separate APK with all of the shared pieces.  As of Developer Preview 2, this reduces the size of your APK by nearly 10MB, and saves 27MB of on-device storage per ARCore application installed (after the first one).

When ARCore 1.0 is released this requirement will be invisible to users.
