### ISSUE TITLE
How to do coordinate transform (coordinate system fusion) between two mobile phones that running ARCore, based on the shared cloud anchor?

### ISSUE THREAD

**Issue by Kyrie-Zhao** [google-ar/arcore-android-sdk#937]
The "getpose" for camera and anchor means the transform from local coordinate to the world coordinate. I am still confused about local coordinate, world coordinate and the quaternion in the "getpose" api after searching multiple materials on the internet. 

Now my goal is: To let two (or more) mobile phones that run ARCore know each other's pose ([x, y, z, quaternion]), In another word,  Let those devices be in a same world coordinate system based on the anchor (cause the anchor is the only thing that in common for two devices' world coordinate, I guess it shall be the breakthrough point). I want to read the real-time pose (coordinate, orientation) for each of them. further more, To judge whether two/more devices have common FoV based on the poses of them (of course in a same coordinate system).

**Comment by devbridie** [comment]
Documenting high level thoughts for anybody coming across this in search,

The shared anchor has a shared pose, and each viewer has their own camera pose. 

On a high level, one would:

1. Compose a new coordinate system using [`Pose.getX/Y/ZAxis`](https://developers.google.com/ar/reference/java/com/google/ar/core/Pose#getXAxis()) and origin [`Pose.getTranslation`](https://developers.google.com/ar/reference/java/com/google/ar/core/Pose#getTranslation()).
2. Calculate viewer A's relative translation relative to the new coordinate system and broadcast to B.
3. B can calculate A's pose relative to the shared anchor.

[Just a Line](https://github.com/googlecreativelab/justaline-android) is a little wordy, but you could look there for some implementation.

Closing due to age.
