### ISSUE TITLE
Honor 7X support

### ISSUE THREAD

**Issue by 32Vache** [google-ar/arcore-android-sdk#944]
Arcore can support Honor 7X phones im pretty sure (4gb ram, cpu HiSilicon Kirin 659, Android 9)
please add it to the compability list, need that to play the new minecraft earth

**Comment by boehm-e** [comment]
I had a 7x and it had no gyroscope (some forum spoke about software disabled gyroscope --'). So if it is still disabled (or if it does not have one), it will never work.

**Comment by TheUNkilled123** [comment]
Hello, I'm just here to report that the device DOES have a working gyroscope, it was just disabled some time after the phone was released. But it's been a while since it got enabled, so I don't see a reason why it shouldn't be supported. If anyone sees this who can change that and add it to the supported list, that would be awesome!

**Comment by VacheMeuh** [comment]
Can confirm, after looking in a phone sensor checker app there is a gyroscope (app is in french but that doesn't matter) 
![Screenshot_20200329_182807_com wered sensorsmultitool](https://user-images.githubusercontent.com/42336759/77854552-4bbaad80-71eb-11ea-99cc-660a914f5989.jpg)

**Comment by ZeProf2Code** [comment]
Please add this ! 👍

**Comment by devbridie** [comment]
No updates to share on this device, unfortunately. #89 tracks ARCore device support requests.
