### ISSUE TITLE
How to place 3d object when camera opened in ar core in android studio?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-android-sdk#97]
Iam working and analysing  sample ar core provided in samples.in java_arcore_hello_ar project when i touch the screen only object was created and anchored. but i want to place object before touch after that place anchor of the object when i touch.

**Comment by inio** [comment]
I'm not sure I understand the question, could you provide a little more context?  Maybe walk us through the user interaction you're trying to achieve.

**Comment by ArigarasuthanRepo** [comment]
I want to load object before touch the detected planes.  after that i want put an anchor of the loaded object  when i touch.

**Comment by ArigarasuthanRepo** [comment]
In 

> java_arcore_hello_ar 

sample objects created via touch the detected planes.

**Comment by robertjuh** [comment]
I'm not sure if i understant the question but im currently working with the web version and in example: 
https://google-ar.github.io/three.ar.js/examples/spawn-at-surface.html
They do: cube.position.set(10000, 10000, 10000); during the initiation of the project (it's so far away that it's invisible). Then when you tap somewhere, the object moves to the position you tap.

So from what i understand what you want is: cube.position.set(0,0,-1); So that it appears in front of you right when you open the app?

Well this is javascript and you want Java, so i'm not too  sure about that. Maybe you could try looking at:
 mSession.addAnchor(hit.getHitPose()))); in the "onDrawFrame(GL10 gl)" method and then change the getHitPose to a hardcoded location and call the function during initiation?

Please correct me if i'm wrong.

**Comment by robertjuh** [comment]
found this for unity:
https://stackoverflow.com/questions/46858950/placing-objects-right-in-front-of-camera

**Comment by inio** [comment]
Does the response to #103 help answer this?
